/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.ActionEmploye.GestionActionEmployee;
import com.raven.model.StatusType;
import com.raven.projet_java_s2.emprunt;
import com.raven.swing.ScrollBar;
import java.awt.Color;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import com.raven.projet_java_s2.employee;

/**
 *
 * @author USER
 */
public class AfficherEmprunts extends javax.swing.JPanel {

    /**
     * Creates new form AfficherEmprunts
     */
    public AfficherEmprunts() {
          initComponents();
        //  add row table
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
         Vector<emprunt> o = new Vector<>();
         String debut=null;
         String type;
            try {
                GestionActionEmployee g = new GestionActionEmployee();
                o=g.AfficherEmprunt();
            for (emprunt emp : o) {
                 String id=emp.getEmprunt_id()+"           "+emp.getOuvrage_id()+"                  "+emp.getAbonne_id();
                 int retard=emp.getRetard();
                 float amende=emp.getAmende();
                 DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                 if (emp.getDate_debut()!=null)
                 { debut = emp.getDate_debut().format(formatter);}
                  
                String fin_prevue = emp.getDate_fin_prevu().format(formatter);
                String fin_effective = emp.getDate_fin_effective().format(formatter);
              
                String date=fin_prevue+"    "+fin_effective;
                  String a=retard+"             "+amende;
                table.addRow(new Object[]{id,debut,date, a,StatusType.ATTENTE });
                  }
            }
            catch (NumberFormatException e) {

            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jLabel2 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Tous les emprunts");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 270, -1));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 127, 127));
        panelBorder1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 20, -1, -1));

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id   ouvrage_id   abonne_id", "date_debut", "date_fin_prevu     date_fin_effective", "retard    amende"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);

        panelBorder1.add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 930, 370));

        add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 970, 420));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesemployes/background employe (1).jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 830));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.raven.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
