/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.ActionEmploye.GestionActionEmployee;
import com.raven.main.Dictionnaire;
import com.raven.main.Gerer_ouvrage;
import com.raven.main.Livre;
import com.raven.main.Magazine;
import com.raven.main.Ouvrage;
import com.raven.model.StatusType;
import com.raven.projet_java_s2.emprunt;
import com.raven.reservation.Emprunts;
import com.raven.swing.ScrollBar;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author USER
 */
public class AjouterEmprunt extends javax.swing.JPanel {

    /**
     * Creates new form AjouterEmprunt
     */
    public AjouterEmprunt() {
          initComponents();
        //  add row table
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
         Vector<Ouvrage> o = new Vector<>();
         String debut=null;
         String type;
            try {
                    Gerer_ouvrage g = new Gerer_ouvrage();
                o=g.obtenir_ouvrage_disponible();
            for (Ouvrage ouv : o) {
                 int id=ouv.getId();
                 String titre=ouv.getTitle();
                 String genre=ouv.getGenre();
                 DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                 String formattedDate = ouv.getDate_publication().format(formatter);
                   if (ouv instanceof Livre)
                   {
                       type="Livre";
               
                   }
                   else if (ouv instanceof Dictionnaire)
                   {
                       type="Dictionnaire";

                   }
                   else if (ouv instanceof Magazine)
                   {
                       type="Magazine";

                   }
                   else 
                   {
                       type="Livre Audio";

                   }
                table.addRow(new Object[]{id,type+"  "+genre,titre,genre,formattedDate,StatusType.ATTENTE });
                  }
            }
            catch (NumberFormatException e) {

            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 255));
        jToggleButton1.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton1.setText("CLICK");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 94, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 153));
        jLabel1.setText("Ajouter des emprunts");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 108, 236, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 171, -1));

        jLabel2.setForeground(new java.awt.Color(204, 0, 153));
        jLabel2.setText("ABONNE_ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 0, 153));
        jLabel3.setText("OUVRAGE_ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 171, -1));

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_ouvrage", "type   genre", "titre", "date_publication"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);

        add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 142, 500, 320));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("Les ouvrages disponible");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 108, 180, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 289, 130, 42));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("Ajouter emprunt");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 350, 76));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesemployes/background employe (1).jpg"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1390, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String abb_id = jTextField1.getText();
        String ouv_d  = jTextField2.getText();
        String regexNumeric = "\\d+";
        if (abb_id.isEmpty() || ouv_d.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }  else if (!ouv_d.matches(regexNumeric) || !abb_id.matches(regexNumeric) ) {
            JOptionPane.showMessageDialog(null, "Les champs abb_id et ouvrage_id de pages doivent contenir uniquement des chiffres.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        Boolean o;
         String debut=null;
         String type;
            try {
               LocalDate dateAujourdhui=LocalDate.now();
               Emprunts g = new Emprunts();
                int ouvrageId = Integer.parseInt(jTextField2.getText());
                int abonneId = Integer.parseInt(jTextField1.getText());
                 o = g.enregistrerEmprunt(ouvrageId, abonneId, dateAujourdhui);            
                 if (o)
                 {
                     jLabel6.setText("succes");
                 }
                 else
                 {
                   JOptionPane.showMessageDialog(null, "Veuillez saisie un id_ouvrage et id_abonne disponnible", "Erreur", JOptionPane.ERROR_MESSAGE);
                 }
            }       
            catch (NumberFormatException e) {

            }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
