/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import Livraison.GererLivraison;
import Livraison.Livraison;
import com.raven.model.Model_Card;
import com.raven.model.StatusType;
import com.raven.swing.ScrollBar;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.GridLayout;

/**
 *
 * @author RAVEN
 */
public class ChoisirReservation extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
public ChoisirReservation() {
    initComponents();
    spTable.setVerticalScrollBar(new ScrollBar());
    spTable.getVerticalScrollBar().setBackground(Color.WHITE);
    spTable.getViewport().setBackground(Color.WHITE);
    JPanel p = new JPanel();
    p.setBackground(Color.WHITE);
    spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
    
    // Ajouter les données dans le tableau
    GererLivraison g = new GererLivraison();
    Vector<Livraison> livraisons = new Vector<>();
    livraisons = g.obtenir_livraisons();
    for (int i = 0; i < livraisons.size(); i++) {
        table.addRow(new Object[]{
            livraisons.get(i).getAbonne_id(),
            livraisons.get(i).getOuvrage_id(),
            livraisons.get(i).getAdresse() + " " + livraisons.get(i).getIntruction(),
            livraisons.get(i).getNum(),
            StatusType.ATTENTE
        });
    }
    
    // Ajouter l'écouteur de sélection de ligne
    addRowClickListener();
}

    
    // </editor-fold>
 int id_livraison;
Object id;
 int selectedRow;
boolean visible=false;
   private void addRowClickListener() {
        table.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                     selectedRow = table.getSelectedRow();
                    if (selectedRow != -1) {
                        // Récupérer les informations de la ligne sélectionnée
                        Object id = table.getValueAt(selectedRow, 0);
                        Object ouvrageId = table.getValueAt(selectedRow, 1);
                        Object adresse = table.getValueAt(selectedRow, 2);
                        Object instruction = table.getValueAt(selectedRow, 3);
                        displayInformationWindow(id, ouvrageId, adresse, instruction);
                       GererLivraison g = new GererLivraison();
                       id_livraison = g.obtenir_id_livraison(Integer.parseInt(id.toString()), Integer.parseInt(ouvrageId.toString()));
                    }
                }
            }
            
        });
    }
       private JButton button1;
    private JButton button2;

private void displayInformationWindow(Object id, Object ouvrageId, Object adresse, Object instruction) {
    JFrame frame = new JFrame("Informations de Livraison");
    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    frame.setSize(400, 200);
    JPanel panel = new JPanel(new GridLayout(0, 1)); // 1 colonne, lignes automatiques

    JLabel labelAdresse = new JLabel("Adresse du client est la suivante : " + adresse);
    JLabel labelInstruction = new JLabel("Instruction : " + instruction);
    
    JButton button1 = new JButton("COMMANDE RECUPEREE");
    JButton button2 = new JButton("FAIRE UNE DECLARATION");
    
    panel.add(labelAdresse);
    panel.add(labelInstruction);
    panel.add(button1);
    panel.add(button2);

    frame.add(panel);
    frame.setVisible(true);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jLabel2 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selectionner une reservation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 661, -1));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 1061, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Toutes les livraisons");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 197, -1));

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Abonne_id", "Ouvrage_id", "Adresse et instruction", "numtel", "etat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);

        add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 680, 290));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesemployes/background livreur (1).jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 840));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.raven.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
