/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.projet_java_s2.abonne_service;
import com.raven.projet_java_s2.history;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class ConsulterHistorique extends javax.swing.JPanel {

    /**
     * Creates new form ConsulterHistorique
     */
    public ConsulterHistorique() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        Vector<history> vh = new Vector<>();
                    vh=abonne_service.get_all_history();

         for(history h:vh)
        {
            Object objet[]={h.getAction_id(),h.getAction(),h.getDate_action(),h.getEmployee_id(),h.getAbonne_id()};
            model.addRow(objet);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtId2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Action id", "Action", "Date", "Employee id", "Abonne id"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 710, 360));

        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("EMPLOYEE_ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, -1));
        add(txtId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 102, -1));

        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("ABONNE_ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 80, -1));
        add(txtId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 102, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 100, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Historique");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 180, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesemployes/background employe (1).jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1310, 870));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    int rowCount = model.getRowCount();
     for (int i = rowCount - 1; i >= 0; i--) {
        model.removeRow(i);
    }
    Vector<history> vh = new Vector<>();
    if (!txtId1.getText().isEmpty() && txtId2.getText().isEmpty()) {
        vh = abonne_service.get_all_history(Integer.parseInt(txtId1.getText()));
        if (vh.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Wrong Information");
        }
    } else if (!txtId2.getText().isEmpty() && txtId1.getText().isEmpty()) {
        vh = abonne_service.get_all_history(Integer.parseInt(txtId2.getText()), "ha");
        if (vh.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Wrong Information");
        }
    } else if (!txtId2.getText().isEmpty() && !txtId1.getText().isEmpty()) {
        vh = abonne_service.get_all_history(Integer.parseInt(txtId1.getText()), Integer.parseInt(txtId2.getText()));
        if (vh.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Wrong Information");
        }
    } else {
        // Gérer le cas où aucun des champs n'est rempli
    }
    
    // Ajouter les nouvelles lignes à la table
    for (history h : vh) {
        Object objet[] = {h.getAction_id(), h.getAction(), h.getDate_action(), h.getEmployee_id(), h.getAbonne_id()};
        model.addRow(objet);
    }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtId2;
    // End of variables declaration//GEN-END:variables
}
