/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.main.LIBRAIRIE;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import static java.lang.System.in;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
    import javax.swing.SwingUtilities;

/**
 *
 * @author USER
 */
public class MonCompte extends javax.swing.JPanel {

    /**
     * Creates new form MonCompte
     */
    public MonCompte() {
        initComponents();
                chargerDonneesEmploye();

    }
     ResultSet rs = null;
        PreparedStatement st = null;
        com.sun.jdi.connect.spi.Connection connection = null;
    


private void chargerDonneesEmploye() {
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        Connection connection = LIBRAIRIE.getConnection();
        String sql = "SELECT nom, prenom, salaire, date_naissance, cin, image FROM employee WHERE employee_id = ?";
        pstmt = connection.prepareStatement(sql);
        pstmt.setInt(1, 20);
        rs = pstmt.executeQuery();
        if (rs.next()) {
            jTextField1.setText(rs.getString("nom"));
            jTextField2.setText(rs.getString("prenom"));
            jTextField3.setText(String.valueOf(rs.getInt("cin")));
            jTextField4.setText(String.valueOf(rs.getInt("salaire")));
            jTextField5.setText(rs.getDate("date_naissance").toString());

            byte[] imgBytes = rs.getBytes("image");
           if (imgBytes != null) {
    ImageIcon imageIcon = new ImageIcon(imgBytes);
    jLabel1.setIcon(imageIcon);
} else {
                System.out.println("Image non trouvée ou erreur de lecture.");
                jLabel1.setIcon(null);
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(204, 0, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(204, 0, 153));
        jLabel2.setText("NOM");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 0, 153));
        jLabel3.setText("PRENOM");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setForeground(new java.awt.Color(204, 0, 153));
        jLabel4.setText("CIN");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 40, -1));

        jLabel5.setForeground(new java.awt.Color(204, 0, 153));
        jLabel5.setText("SALAIRE");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel6.setForeground(new java.awt.Color(204, 0, 153));
        jLabel6.setText("DATE NAISSANCE");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("jTextField1");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 162, -1));

        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("jTextField1");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 162, -1));

        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("jTextField1");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 162, -1));

        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("jTextField1");
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 162, -1));

        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("jTextField1");
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 162, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 176, 217));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("MON COMPTE");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 280, 65));

        jLabel9.setForeground(new java.awt.Color(204, 0, 153));
        jLabel9.setText("MODIFIER COMPTE");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 138, -1));

        jToggleButton2.setBackground(new java.awt.Color(255, 204, 255));
        jToggleButton2.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton2.setText("OK");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 70, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesemployes/background employe (1).jpg"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1310, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
