/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.main.Dictionnaire;
import com.raven.main.Gerer_ouvrage;
import com.raven.main.LIBRAIRIE;
import com.raven.main.Livre;
import com.raven.main.Magazine;
import com.raven.main.Ouvrage;
import com.raven.main.Reservation;
import com.raven.model.StatusType;
import com.raven.reservation.GererActionabonne1;
import com.raven.swing.ScrollBar;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author USER
 */
public class ReserverOuvrage extends javax.swing.JPanel {

    /**
     * Creates new form ReserverOuvrage
     */
    public ReserverOuvrage() {
         initComponents();
        //  add row table
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
         Vector<Ouvrage> o = new Vector<>();
         String debut=null;
         String type;
            try {
                    GererActionabonne1 g = new GererActionabonne1();
                o=g.AfficherOuvrageARerserver();
            for (Ouvrage ouv : o) {
                 int id=ouv.getId();
                 String titre=ouv.getTitle();
                 String genre=ouv.getGenre();
                 DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                 String formattedDate = ouv.getDate_publication().format(formatter);
                   if (ouv instanceof Livre)
                   {
                       type="Livre";
                   }
                   else if (ouv instanceof Dictionnaire)
                   {
                       type="Dictionnaire";

                   }
                   else if (ouv instanceof Magazine)
                   {
                       type="Magazine";

                   }
                   else 
                   {
                       type="Livre Audio";

                   }
                table.addRow(new Object[]{id,type+"  "+genre,titre,genre,formattedDate,StatusType.ATTENTE });
                  }
            }
            catch (NumberFormatException e) {

            }
    }
     public String getAbonneById(int abonneId) {
        String query = "SELECT nom, prenom FROM abonne WHERE id = ?";
        
        String nom_complet=null;
        try (
                Connection conn = LIBRAIRIE.getConnection();

             PreparedStatement pstmt = conn.prepareStatement(query)) {
            pstmt.setInt(1, abonneId);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                 nom_complet=nom+" "+prenom;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return nom_complet; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 153));
        jLabel3.setText("OUVRAGE_ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 99, -1));

        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 171, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 153));
        jLabel5.setText("ABONNE_ID");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 87, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 262, 279, 556));

        jToggleButton1.setBackground(new java.awt.Color(255, 204, 255));
        jToggleButton1.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton1.setText("CLICK");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 153));
        jLabel1.setText("Reserver");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 120, -1));

        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 171, -1));

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_ouvrage", "type   genre", "titre", "date_publication"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);

        add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 112, 580, 300));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesemployes/background employe (1).jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String abb_id = jTextField1.getText();
         LocalDateTime date_retour ;
         String ouv_d  = jTextField2.getText();
        String regexNumeric = "\\d+";
        int abb_id1 = Integer.parseInt(jTextField1.getText());
        int ouvr_id2 = Integer.parseInt(jTextField2.getText());
        try
        {
           
        if (abb_id.isEmpty() || ouv_d.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }  else if (!ouv_d.matches(regexNumeric) || !abb_id.matches(regexNumeric) ) {
            JOptionPane.showMessageDialog(null, "Les champs abb_id et ouvrage_id de pages doivent contenir uniquement des chiffres.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
      
        else    if(!existe_abonne(abb_id1))
            {
                JOptionPane.showMessageDialog(null, "Saisir un abonne existant et disponible.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            else if(!existe_ouvrage(ouvr_id2))
            {
                JOptionPane.showMessageDialog(null, "Saisir un ouvrage existant et disponible.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }

            else
            {
                Boolean o;
                String debut=null;
                String type;
                try {
                    LocalDate dateAujourdhui=LocalDate.now();
                    GererActionabonne1 g = new GererActionabonne1();
                    int ouvrageId = Integer.parseInt(jTextField2.getText());
                    int abonneId = Integer.parseInt(jTextField1.getText());
                    date_retour=g.reserverOuvrage(abonneId, ouvrageId);
                    if (date_retour !=null)
                    {
                        jLabel6.setText("LIVRE RESERVE , IL SERA PRET LE : "+date_retour);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Veuillez saisi un id_ouvrage et id_abonne disponnible", "Erreur", JOptionPane.ERROR_MESSAGE);
                    }
                }
                catch (NumberFormatException e) {
                    
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReserverOuvrage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed
   public static boolean existe_abonne(int abonne_id) throws SQLException  
   {
        String query = "SELECT COUNT(*) FROM abonne WHERE abonne_id = ?";
        Connection connection = LIBRAIRIE.getConnection();
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setInt(1, abonne_id);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    int count = resultSet.getInt(1);
                    return count > 0;
                }
            }
        }
        return false;
    }
     public static boolean existe_ouvrage(int ouvrage_id) throws SQLException  {
        Connection connection = LIBRAIRIE.getConnection();
        String query = "SELECT COUNT(*) FROM ouvrages WHERE ouvrage_id = ? and disponibilite=false";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setInt(1, ouvrage_id);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    int count = resultSet.getInt(1);
                    return count > 0;
                }
            }
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
