/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.ActionEmploye.GestionActionEmployee;
import com.raven.main.Dictionnaire;
import com.raven.main.Gerer_ouvrage;
import com.raven.main.Livre;
import com.raven.main.Magazine;
import com.raven.main.Ouvrage;
import com.raven.model.StatusType;
import com.raven.projet_java_s2.emprunt;
import com.raven.reservation.Emprunts;
import com.raven.swing.ScrollBar;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author USER
 */
public class RetournerLivre extends javax.swing.JPanel {

    /**
     * Creates new form RetournerLivre
     */
    public RetournerLivre() {
           initComponents();
        //  add row table
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
         Vector<emprunt> o = new Vector<>();
         String debut=null;
         String type;
            try {
                GestionActionEmployee g = new GestionActionEmployee();
                o=g.AfficherEmprunt();
            for (emprunt emp : o) {
                 String id=emp.getEmprunt_id()+"           "+emp.getOuvrage_id()+"    "+emp.getAbonne_id();
                 int retard=emp.getRetard();
                 float amende=emp.getAmende();
                 DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                 if (emp.getDate_debut()!=null)
                 { debut = emp.getDate_debut().format(formatter);}
                  
                String fin_prevue = emp.getDate_fin_prevu().format(formatter);
                String fin_effective = emp.getDate_fin_effective().format(formatter);
              
                String date=fin_prevue+fin_effective;
                  String a=retard+"    "+amende;
                table.addRow(new Object[]{id,debut,date, a,StatusType.ATTENTE });
                  }
            }
            catch (NumberFormatException e) {

            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 153));
        jLabel1.setText("Retourner emprunt");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 150, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 153));
        jLabel3.setText("OUVRAGE_ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 90, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 210, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Liste des emprunts");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 290, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 153));
        jLabel5.setText("ABONNE_ID");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 90, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 247, 130, 42));

        jToggleButton1.setBackground(new java.awt.Color(255, 204, 255));
        jToggleButton1.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton1.setText("CLICK");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 94, -1));

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id   ouvrage_id   abonne_id", "date_debut", "date_fin_prevu     date_fin_effective", "retard    amende"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);

        add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 740, 340));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesemployes/background employe (1).jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String abb_id = jTextField1.getText();
        String ouv_d  = jTextField2.getText();
        String regexNumeric = "\\d+";
        if (abb_id.isEmpty() || ouv_d.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }  else if (!ouv_d.matches(regexNumeric) || !abb_id.matches(regexNumeric) ) {
            JOptionPane.showMessageDialog(null, "Les champs abb_id et ouvrage_id de pages doivent contenir uniquement des chiffres.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        Boolean o;
        String debut=null;
        String type;
        try {
            LocalDate dateAujourdhui=LocalDate.now();
            Emprunts g = new Emprunts();
            int ouvrageId = Integer.parseInt(jTextField2.getText());
            int abonneId = Integer.parseInt(jTextField1.getText());
            o = g.enregistrerRetour(ouvrageId, abonneId);
            if (o)
            {
                jLabel6.setText("succes");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Veuillez saisie un id_ouvrage et id_abonne disponnible", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
