/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.main.Dictionnaire;
import com.raven.main.Gerer_ouvrage;
import com.raven.main.LIBRAIRIE;
import com.raven.main.Livre;
import com.raven.main.LivreAudio;
import com.raven.main.Magazine;
import com.raven.main.Ouvrage;
import com.raven.model.StatusType;
import com.raven.swing.ScrollBar;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author USER
 */
public class SignalerVol extends javax.swing.JPanel {

    /**
     * Creates new form SignalerVol
     */
    public SignalerVol() {
initComponents();
        //  add row table
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
         Vector<Ouvrage> o = new Vector<>();
         String type;
            try {
                Gerer_ouvrage g = new Gerer_ouvrage();
                o=g.lister_tous_les_ouvrages();
                 type="Livre";
            for (Ouvrage ouvrage : o) {
                if (ouvrage instanceof Livre) {
                    Livre l = (Livre) ouvrage;
                     type="Livre";
                    
                } else if (ouvrage instanceof Magazine) {
                    Magazine magazine = (Magazine) ouvrage;
                    type="Magazine";

                } 
                else if (ouvrage instanceof LivreAudio) {
                    LivreAudio la = (LivreAudio) ouvrage;
                     type="LivreAudio";

                } else if (ouvrage instanceof Dictionnaire ) {
                    Dictionnaire dict = (Dictionnaire) ouvrage;
                    type="Dictionnaire";
                } 
       table.addRow(new Object[]{ouvrage.getId(), ouvrage.getTitle(),type,ouvrage.getGenre(),ouvrage.isDisponibilite(), StatusType.ATTENTE});

                  }


            }
            catch (NumberFormatException e) {

            }    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resultat = new javax.swing.JLabel();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jLabel4 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swing.Table();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setForeground(new java.awt.Color(204, 0, 153));
        jButton1.setText("CLICK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 237, -1, -1));

        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 179, 126, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 153));
        jLabel1.setText("OUVRAGE_ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 181, 108, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Signaler Vol");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 326, 54));

        resultat.setForeground(new java.awt.Color(255, 255, 255));
        add(resultat, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 813, -1, -1));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 127, 127));

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Titre", "Type", "Genre", "Disponibilite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(491, 491, 491))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 130, 640, 340));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesemployes/background employe (1).jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 830));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String regexNumeric = "\\d+";
        String id = jTextField1.getText();
        Boolean disponibilite=false;
         String requete = "SELECT disponibilite FROM ouvrages WHERE ouvrage_id = ?";
              try {
        Connection connection = LIBRAIRIE.getConnection();
        PreparedStatement preparedStatement = connection.prepareStatement(requete);
        preparedStatement.setInt(1, Integer.parseInt(id));
        ResultSet resultSet = preparedStatement.executeQuery();
          if (resultSet.next())
          {
                      disponibilite = resultSet.getBoolean("disponibilite");
          }
       
          }
              catch(Exception ex)
              {
                  JOptionPane.showMessageDialog(null, ex);
              }
          System.out.println(disponibilite);
        if (id.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else if( !id.matches(regexNumeric))
        {
            JOptionPane.showMessageDialog(null, "Veuillez saisir  id de  type numerique", "Erreur", JOptionPane.ERROR_MESSAGE);

        }
        else if (disponibilite==true)
        {
           JOptionPane.showMessageDialog(null, "Vous ne pouvez pas signaler un livre disponible ", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
                Gerer_ouvrage g=new Gerer_ouvrage();
            try {
                boolean supp = g.Signaler_vol(Integer.parseInt(id));
                if (supp) {
                    resultat.setText("signale avec succès.");
                } else {
                    resultat.setText("Saisir un id existant ");
                }
            }
            catch (NumberFormatException e) {
                resultat.setText(id);

            }}
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private com.raven.swing.PanelBorder panelBorder1;
    private javax.swing.JLabel resultat;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
