/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.formAbonne;

import biblio.AbonneService;
import static biblio.EmployeService.getConnection;
import biblio.Reservation1;
import com.raven.main.Reservation;
import com.raven.modelAbonne.StatusType;
import com.raven.reservation.GererActionabonne1;
import static com.raven.service.ServiceUser.userID;
import com.raven.swingAbonne.ScrollBar;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author USER
 */
public class AnnulerReservation extends javax.swing.JPanel {

    /**
     * Creates new form AnnulerReservation
     */
        int ouvrageId;

    public AnnulerReservation() {
        initComponents();
      
        //  add row table
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
         String debut=null;
            table1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) { 
                    JTable target = (JTable)e.getSource();
                    int selectedRow = target.getSelectedRow();
                     ouvrageId = (int)table1.getValueAt(selectedRow, 1);
                    jTextField2.setText(String.valueOf(ouvrageId));
                }
            }
        });
    
         Vector<Reservation> o = new Vector<>();
         String type;
         
            try {
            GererActionabonne1 g=new GererActionabonne1();
                o=g.afficherReservationsUtilisateurPourAnnule(12);
                         System.out.println("lala"+o.size());

            for (Reservation res : o) {
                 String nom_com=getAbonneById(res.getAbonne_id());
                 DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                String formattedDate = res.getDate_reservation().format(formatter);
table1.addRow(new Object[]{ nom_com, res.getOuvrage_id(), res.getOrdre_attente(),formattedDate,StatusType.APPROVED });
                  }
            }
            catch (NumberFormatException e) {

            }
    }
    
      public String getAbonneById(int abonneId) {
        String query = "SELECT nom, prenom FROM abonne WHERE abonne_id = ?";
        
        String nom_complet=null;
        try (
           Connection conn=getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            pstmt.setInt(1, abonneId);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                 nom_complet=nom+" "+prenom;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return nom_complet;    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swingAbonne.Table();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        spTable2 = new javax.swing.JScrollPane();
        table1 = new com.raven.swingAbonne.Table();
        jLabel2 = new javax.swing.JLabel();

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom complet    ", "ouvrage_id", "ordre", "date_reservation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(185, 164, 117));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, 150, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(101, 61, 3));
        jLabel1.setText("Annuler Reservation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 300, 40));

        jTextField2.setText("jTextField1");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 200, 50));

        spTable2.setBorder(null);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom complet    ", "ouvrage_id", "ordre", "date_reservation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable2.setViewportView(table1);

        add(spTable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 790, 350));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesabonnes/background books (2).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(table1.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un ouvrage.", "Erreur", JOptionPane.ERROR_MESSAGE);
        } 
        else
        {
        LocalDateTime date_retour ;
        String ouv_d  = jTextField2.getText();
        String regexNumeric = "\\d+";
      

        Boolean o;
        String debut=null;
        String type;
        try {
            GererActionabonne1 g=new GererActionabonne1();
            int ouvrageId = Integer.parseInt(jTextField2.getText());
            Boolean a=g.annulerReservation(12, ouvrageId);
            if (a !=null)
            {
   JOptionPane.showMessageDialog(null, "Succes", "", JOptionPane.YES_OPTION);            }
            else
            {
                JOptionPane.showMessageDialog(null, "Veuillez saisie un id_ouvrage et id_abonne disponnible dans reservation"
                    + "Sinon le livre a ete annule ", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e) {

        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JScrollPane spTable2;
    private com.raven.swingAbonne.Table table;
    private com.raven.swingAbonne.Table table1;
    // End of variables declaration//GEN-END:variables
}
