/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.formAbonne;

import biblio.AbonneService;
import biblio.Dictionnaire;
import biblio.Livre;
import biblio.Livreaudio;
import biblio.Magazine;
import biblio.Ouvrage;
import static com.raven.service.ServiceUser.userID;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class CommenterOuvrage extends javax.swing.JPanel {
AbonneService as=new AbonneService();
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.S");
Vector<Ouvrage> vo=as.getAllOuvrages();

public void setvo(Vector<Ouvrage> vo){
    this.vo=vo;
    afficher(vo);
}
    /**
     * Creates new form CommenterOuvrage
     */
    public CommenterOuvrage() {
        initComponents();
       afficher(as.getAllOuvrages());

    }

    public void afficher(Vector<Ouvrage> vo){
    DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
    model.setRowCount(0);
    String type="";
    for(Ouvrage o:vo){
       if(o instanceof Livre){
           type="livre";
       }else if(o instanceof Livreaudio){
           type="livreaudio";
       }else if(o instanceof Magazine){
           type="magazine";
       }else if(o instanceof Dictionnaire){
           type="livre";  
       }     
    model.addRow(new Object[]{
    o.getId(),
    type,
    o.getTitre(),
    o.getDate_publication(),
    o.getGenre(),
    o.getLangue(),
    o.getPrix(),
    o.getEtat()
    });}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setBackground(new java.awt.Color(229, 210, 158));
        jTable4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ouvrage id ", "Type", "Titre", "Date publication", "genre", "langue", "prix", "disponibilite"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setGridColor(new java.awt.Color(185, 164, 117));
        jTable4.setInheritsPopupMenu(true);
        jScrollPane4.setViewportView(jTable4);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 870, 370));

        jButton1.setBackground(new java.awt.Color(154, 113, 21));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Commenter");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 210, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(101, 61, 3));
        jLabel3.setText("Sélectionner un ouvrage et laisser un petit commentaire");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 720, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesabonnes/background books (2).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          // Vérifiez si une seule ligne est sélectionnée
    if (jTable4.getSelectedRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "Veuillez sélectionner un ouvrage.", "Erreur", JOptionPane.ERROR_MESSAGE);
    } else if (jTable4.getSelectedRowCount() > 1) {
        JOptionPane.showMessageDialog(null, "Veuillez sélectionner un seul ouvrage et pas plusieurs.", "Erreur", JOptionPane.ERROR_MESSAGE);
    } else {
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        int idOuvrage = Integer.parseInt(model.getValueAt(jTable4.getSelectedRow(),0).toString());
        System.out.println("ID de l'ouvrage sélectionné : " + idOuvrage);
        Commenterr m = new Commenterr(userID,idOuvrage);
        m.setVisible(true);
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
