/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.formAbonne;

import biblio.AbonneService;
import biblio.Dictionnaire;
import static biblio.EmployeService.getConnection;
import biblio.Emprunt;
import biblio.Livre;
import biblio.Livreaudio;
import biblio.Magazine;
import biblio.Ouvrage;
import static com.raven.service.ServiceUser.userID;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class EmprunterLivre extends javax.swing.JPanel {
AbonneService as=new AbonneService();
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.S");
Vector<Ouvrage> vo=as.getAllOuvrages();
public void setvo(Vector<Ouvrage> vo){
    this.vo=vo;
    afficher(vo);
}
    /**
     * Creates new form EmprunterLivre
     */
    public EmprunterLivre() {
        initComponents();
        afficher(as.getAllOuvrages());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(919, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setBackground(new java.awt.Color(229, 210, 158));
        jTable4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ouvrage id ", "Type", "Titre", "Date publication", "genre", "langue", "prix", "disponibilite"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 910, 414));

        jButton5.setBackground(new java.awt.Color(154, 113, 21));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("emprunter");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 250, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 61, 3));
        jLabel2.setText("Sélectionner un ouvrage et emprunter le");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 390, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesabonnes/background books (2).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jTable4.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un ouvrage.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else if(jTable4.getSelectedRowCount()>1)
        {
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un seul ouvrage et pas plusieurs.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else{
            AbonneService as=new AbonneService();
            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
            int id=Integer.parseInt(model.getValueAt(jTable4.getSelectedRow(),0).toString());
            if(!as.getOuvrage(id).getEtat().equals("disponible")){
                JOptionPane.showMessageDialog(null, "cet Ouvrage est déjà emprunté", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            else{
                String x=as.emprunter(new Emprunt(as.getAbonne(userID),as.getOuvrage(id),LocalDateTime.now().format(formatter).toString(),LocalDateTime.now().plusDays(7).format(formatter).toString(),LocalDateTime.now().plusDays(7).format(formatter).toString(),"en cours",0,0));
                if(x.equals("Emprunt effectué avec succès")){
                    JOptionPane.showMessageDialog(null, x, "succès", JOptionPane.DEFAULT_OPTION);
                    DemanderLivraison d=new DemanderLivraison(id,userID);
                    d.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, x, "Erreur", JOptionPane.ERROR_MESSAGE);
                }
                vo=as.getAllOuvrages();
                afficher(vo);
            }}
    }//GEN-LAST:event_jButton5ActionPerformed

    public void afficher(Vector<Ouvrage> vo){
    DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
    model.setRowCount(0);
    String type="";
    for(Ouvrage o:vo){
       if(o instanceof Livre){
           type="livre";
       }else if(o instanceof Livreaudio){
           type="livreaudio";
       }else if(o instanceof Magazine){
           type="magazine";
       }else if(o instanceof Dictionnaire){
           type="livre";  
       }     
    model.addRow(new Object[]{
    o.getId(),
    type,
    o.getTitre(),
    o.getDate_publication(),
    o.getGenre(),
    o.getLangue(),
    o.getPrix(),
    o.getEtat()
    });}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
