/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.formAbonne;
import biblio.*;
import static com.raven.service.ServiceUser.userID;
import java.time.LocalDateTime;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pc
 */
public class GetAllMesCommentaires extends javax.swing.JPanel {

    /**
     * Creates new form GetAllMesCommentaires
     */
    public GetAllMesCommentaires() {
        initComponents();
            afficher();
    }
public void afficher(){
    AbonneService as=new AbonneService();
    Vector<Commentaire> vc=as.getAllMesCommentaires(userID);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    String type="";
    for(Commentaire c:vc){
       if(c.getOuvrage() instanceof Livre){
           type="livre";
       }else if(c.getOuvrage() instanceof Livreaudio){
           type="livreaudio";
       }else if(c.getOuvrage() instanceof Magazine){
           type="magazine";
       }else if(c.getOuvrage() instanceof Dictionnaire){
           type="dictionnaire";  
       }     
    model.addRow(new Object[]{
     c.getId(),
    c.getAbonne().getNom()+" "+c.getAbonne().getPrenom(),
    c.getOuvrage().getTitre(),
    type,
    c.getNbr_etoiles(),
    c.getDescription(),
    c.getDate_commentaire()
    });
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(154, 113, 21));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("recherche un commentaire");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 239, 30));

        jTable1.setBackground(new java.awt.Color(229, 210, 158));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id commentaire", "nom abonné", "titre ouvrage", "type ouvrage", "note", "description", "date commentaire"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 51, 916, -1));

        jButton1.setBackground(new java.awt.Color(154, 113, 21));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("modifier");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 114, 30));

        jButton2.setBackground(new java.awt.Color(154, 113, 21));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("supprimer");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 106, 30));

        jButton3.setBackground(new java.awt.Color(154, 113, 21));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("mes commentaires");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 192, 30));

        jButton4.setBackground(new java.awt.Color(154, 113, 21));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("tous commentaires");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 187, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(101, 61, 3));
        jLabel1.setText("Les Commentaires");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 11, 180, 28));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesabonnes/background books (2).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             // TODO add your handling code here:
         AbonneService as=new AbonneService();
  
        if(jTable1.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un commentaire.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else if(jTable1.getSelectedRowCount()>1)
        {
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un seul commentaire et pas plusieurs.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else{
       
            int id=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
            if (as.getCommentaire(id).getAbonne().getId()==userID)
            {
                
            
            System.out.println(id);
            ModifierComm m=new ModifierComm(as.getCommentaire(id));
            m.setVisible(true);
            afficher();
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "Vous n'avez pas le droit de modifier un commentaire qui n'est pas le votre", "Erreur", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
             // TODO add your handling code here:
             // TODO add your handling code here:
         AbonneService as=new AbonneService();
  
        if(jTable1.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un commentaire.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else if(jTable1.getSelectedRowCount()>1)
        {
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un seul commentaire et pas plusieurs.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else{
        
            int id=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
             if (as.getCommentaire(id).getAbonne().getId()==userID)
            {
              
            if(as.supprimer_commentaire(id)){
                JOptionPane.showMessageDialog(null, "Votre commentaire est supprimé avec succès !", "Succès", JOptionPane.DEFAULT_OPTION);
                afficher();
            }
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "Vous n'avez pas le droit de supprimer un commentaire qui n'est pas le votre", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          // TODO add your handling code here:
         AbonneService as=new AbonneService();
    Vector<Commentaire> vc=as.getAllMesCommentaires(userID);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    String type="";
    for(Commentaire c:vc){
       if(c.getOuvrage() instanceof Livre){
           type="livre";
       }else if(c.getOuvrage() instanceof Livreaudio){
           type="livreaudio";
       }else if(c.getOuvrage() instanceof Magazine){
           type="magazine";
       }else if(c.getOuvrage() instanceof Dictionnaire){
           type="dictionnaire";  
       }     
    model.addRow(new Object[]{
     c.getId(),
    c.getAbonne().getNom()+" "+c.getAbonne().getPrenom(),
    c.getOuvrage().getTitre(),
    type,
    c.getNbr_etoiles(),
    c.getDescription(),
    c.getDate_commentaire()
    });
}
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         AbonneService as=new AbonneService();
    Vector<Commentaire> vc=as.getAllCommentaires();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    String type="";
    for(Commentaire c:vc){
       if(c.getOuvrage() instanceof Livre){
           type="livre";
       }else if(c.getOuvrage() instanceof Livreaudio){
           type="livreaudio";
       }else if(c.getOuvrage() instanceof Magazine){
           type="magazine";
       }else if(c.getOuvrage() instanceof Dictionnaire){
           type="dictionnaire";  
       }     
    model.addRow(new Object[]{
     c.getId(),
    c.getAbonne().getNom()+" "+c.getAbonne().getPrenom(),
    c.getOuvrage().getTitre(),
    type,
    c.getNbr_etoiles(),
    c.getDescription(),
    c.getDate_commentaire()
    });
}
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
