/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.formAbonne;

import biblio.*;
import static biblio.EmployeService.getConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAVEN
 */
public class GetAllOuvrages extends javax.swing.JPanel {
AbonneService as=new AbonneService();
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.S");
Vector<Ouvrage> vo=as.getAllOuvrages();
public void setvo(Vector<Ouvrage> vo){
    this.vo=vo;
    afficher(vo);
}
    /**
     * Creates new form Form_1
     */
    public GetAllOuvrages() {
        initComponents();
        afficher(as.getAllOuvrages());
        intialiser_combobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(101, 61, 3));
        jLabel3.setText("afficher selon la langue:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 510, 150, 20));

        jButton1.setBackground(new java.awt.Color(154, 113, 21));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("afficher tous les ouvrages");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 230, 30));

        jComboBox3.setBackground(new java.awt.Color(154, 113, 21));
        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tous" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 400, -1));

        jButton2.setBackground(new java.awt.Color(154, 113, 21));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("afficher par mots clés");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 200, 30));

        jButton4.setBackground(new java.awt.Color(154, 113, 21));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("afficher par disponibilité");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 190, 30));

        jButton6.setBackground(new java.awt.Color(154, 113, 21));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("afficher selon la note");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 190, 30));

        jComboBox1.setBackground(new java.awt.Color(154, 113, 21));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tous", "livre", "livreaudio", "magazine", "dictionnaire", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 400, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 61, 3));
        jLabel2.setText("afficher selon le type:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 430, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(101, 61, 3));
        jLabel4.setText("afficher selon le genre:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 470, 150, -1));

        jTable4.setBackground(new java.awt.Color(229, 210, 158));
        jTable4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ouvrage id ", "Type", "Titre", "Date publication", "genre", "langue", "prix", "disponibilite"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1030, 350));

        jComboBox2.setBackground(new java.awt.Color(154, 113, 21));
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tous" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 400, -1));

        jButton7.setBackground(new java.awt.Color(154, 113, 21));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("afficher par syllabe");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 200, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(101, 61, 3));
        jLabel1.setText("Nos Ouvrages");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 190, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesabonnes/background books (2).png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        afficher(as.getAllOuvrages());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
         if(jComboBox3.getSelectedItem().toString().equals("tous")){
            vo=as.getAllOuvrages();
        }
        else{
            vo=as.getOuvrageByLangue(jComboBox3.getSelectedItem().toString());
        }
        afficher(vo);
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        motcles ga=new motcles(GetAllOuvrages.this);
        ga.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        afficher(as.getAllOuvragesByDispo());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Afficherselonlanote gr=new Afficherselonlanote(GetAllOuvrages.this);
        gr.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().toString().equals("tous")){
            vo=as.getAllOuvrages();
        }
        else{
            vo=as.getAllOuvragesByType(jComboBox1.getSelectedItem().toString());
        }
        afficher(vo);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        if(jComboBox2.getSelectedItem().toString().equals("tous")){
            vo=as.getAllOuvrages();
        }
        else{
            vo=as.getAllOuvragesByGenre(jComboBox2.getSelectedItem().toString());
        }
        afficher(vo);
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         obtenirouvrage_par_title_part ga=new obtenirouvrage_par_title_part(GetAllOuvrages.this);
        ga.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

public void intialiser_combobox(){
        Connection con=getConnection();
        String sql="select distinct(lower(genre)) genre from ouvrages";
        String sql1="select distinct(lower(langue)) langue from ouvrages";
        ResultSet rs,rs1;
        try{
            PreparedStatement pstm=con.prepareStatement(sql);
            rs=pstm.executeQuery();
            while(rs.next()){
                jComboBox2.addItem(rs.getString("genre"));
            }
            PreparedStatement pstm1=con.prepareStatement(sql1);
            rs1=pstm1.executeQuery();
            while(rs1.next()){
                jComboBox3.addItem(rs1.getString("langue"));
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }
    public void afficher(Vector<Ouvrage> vo){
    DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
    model.setRowCount(0);
    String type="";
    for(Ouvrage o:vo){
       if(o instanceof Livre){
           type="livre";
       }else if(o instanceof Livreaudio){
           type="livreaudio";
       }else if(o instanceof Magazine){
           type="magazine";
       }else if(o instanceof Dictionnaire){
           type="livre";  
       }     
    model.addRow(new Object[]{
    o.getId(),
    type,
    o.getTitre(),
    o.getDate_publication(),
    o.getGenre(),
    o.getLangue(),
    o.getPrix(),
    o.getEtat()
    });}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
