/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.formAbonne;

import biblio.AbonneService;
import biblio.Ouvrage;
import biblio.Reservation1;
import com.raven.modelAbonne.StatusType;
import static com.raven.service.ServiceUser.userID;
import com.raven.swingAbonne.ScrollBar;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author USER
 */
public class Mesnotifications extends javax.swing.JPanel {

    /**
     * Creates new form Mesnotifications
     */
   public Mesnotifications() {
    initComponents();
    //  add row table
    spTable.setVerticalScrollBar(new ScrollBar());
    spTable.getVerticalScrollBar().setBackground(Color.WHITE);
    spTable.getViewport().setBackground(Color.WHITE);
    JPanel p = new JPanel();
    p.setBackground(Color.WHITE);
    spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
    
    Vector<Integer> o = new Vector<>();
    String type;
    
    boolean hasData = false; // Pour vérifier si au moins une des méthodes a des données
    
    try {
        AbonneService g = new AbonneService();
        o = g.NotificationReservationAnnulePourRetard(userID);
        for (Integer res : o) {
            String nom_com = g.obtenir_ouvrage_par_id(res).getTitre();
            table1.addRow(new Object[]{nom_com, g.obtenir_ouvrage_par_id(res).getId(), StatusType.APPROVED });
        }
        if (!o.isEmpty()) {
            hasData = true;
        }
            
    }
    catch (NumberFormatException e) {
       System.out.println(e);
    }
    
    try {
        AbonneService g = new AbonneService();
        o = g.NotificationReservationRetardRes(userID);
        for (Integer res : o) {
            String nom_com = g.obtenir_ouvrage_par_id(res).getTitre();
            table.addRow(new Object[]{nom_com, g.obtenir_ouvrage_par_id(res).getId(), StatusType.APPROVED });
        }
        if (!o.isEmpty()) {
            hasData = true;
        }
        else 
        {
                    table.setVisible(false);

        }
    } catch (NumberFormatException e) {
        
    }
    
 
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swingAbonne.Table();
        jLabel3 = new javax.swing.JLabel();
        spTable1 = new javax.swing.JScrollPane();
        table1 = new com.raven.swingAbonne.Table();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(101, 61, 3));
        jLabel1.setText("Mes notifications ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 360, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 61, 3));
        jLabel2.setText("ouvrages  annulé pour retard");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 280, -1));

        spTable.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titre ouvrage", "ouvrag_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spTable.setViewportView(table);

        add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 510, 67));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(101, 61, 3));
        jLabel3.setText("Nous nous excusons du retard , le livre que vous avez reservé fera un petit retard");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 520, -1));

        spTable1.setBorder(null);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "titre ouvrage", "ouvrage_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable1.setViewportView(table1);

        add(spTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 500, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesabonnes/background books (2).png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JScrollPane spTable1;
    private com.raven.swingAbonne.Table table;
    private com.raven.swingAbonne.Table table1;
    // End of variables declaration//GEN-END:variables
}
