/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.formAbonne;

import biblio.AbonneService;
import static biblio.EmployeService.getConnection;
import biblio.Ouvrage;
import biblio.Reservation;
import biblio.Reservation1;
import com.raven.modelAbonne.StatusType;
import static com.raven.service.ServiceUser.userID;
import com.raven.swingAbonne.ScrollBar;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author USER
 */
public class RecupererLivreReserve extends javax.swing.JPanel {

    /**
     * Creates new form RecupererLivreReserve3
     */
    int ouvrageId;
    public RecupererLivreReserve() {
 initComponents();
        //  add row table
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
         String debut=null;
            table.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) { 
                    JTable target = (JTable)e.getSource();
                    int selectedRow = target.getSelectedRow();
                     ouvrageId = (int)table.getValueAt(selectedRow, 1);
                    jTextField2.setText(String.valueOf(ouvrageId));
                }
            }
        });
    
         Vector<Reservation1> o = new Vector<>();
         String type;
            try {
                AbonneService g =new AbonneService();
                o=g.afficherReservationsUtilisateur(userID);
            for (Reservation1 res : o) {
                 String nom_com=getAbonneById(res.getAbonne_id());
                 DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                String formattedDate = res.getDate_reservation().format(formatter);
table.addRow(new Object[]{ nom_com, res.getOuvrage_id(), res.getOrdre_attente(),formattedDate,StatusType.APPROVED });
                  }
            }
            catch (NumberFormatException e) {

            }
    }
    
    
    public String getAbonneById(int abonneId) {
        String query = "SELECT nom, prenom FROM abonne WHERE abonne_id = ?";
        
        String nom_complet=null;
        try (
           Connection conn=getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            pstmt.setInt(1, abonneId);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                 nom_complet=nom+" "+prenom;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return nom_complet;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelBorder1 = new com.raven.swingAbonne.PanelBorder();
        jLabel2 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swingAbonne.Table();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(101, 61, 3));
        jLabel1.setText("Recuperer mon livre que j'ai reservé");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 490, 40));

        panelBorder1.setBackground(new java.awt.Color(229, 210, 158));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 127, 127));
        panelBorder1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        spTable.setBorder(null);

        table.setBackground(new java.awt.Color(229, 210, 158));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom complet    ", "ouvrage_id", "ordre", "date_reservation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);

        panelBorder1.add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 684, 333));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(101, 61, 3));
        jLabel4.setText("OUVRAGE_ID");
        panelBorder1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 157, 92, -1));

        jToggleButton1.setBackground(new java.awt.Color(154, 113, 21));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(242, 242, 242));
        jToggleButton1.setText("CLICK");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        panelBorder1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(101, 61, 3));
        jLabel3.setText("Recuperer");
        panelBorder1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 53, 120, -1));

        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panelBorder1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 171, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(101, 61, 3));
        jLabel6.setText("resultat");
        panelBorder1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 297, 67));

        add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 900, 400));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesabonnes/background books (2).png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if(table.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un ouvrage.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            LocalDateTime date_retour ;
            String ouv_d  = jTextField2.getText();
            String regexNumeric = "\\d+";

            Boolean o;
            String debut=null;
            String type;
            try {
                AbonneService g=new AbonneService();
                int ouvrageId = Integer.parseInt(jTextField2.getText());
                Boolean a=g.recupererLivreReserve(ouvrageId, userID);
                if (a !=null)
                {
                    jLabel6.setText("SUCCES");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Veuillez saisie un id_ouvrage et id_abonne disponnible dans reservation"
                        + "Sinon le livre a ete annule ", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch (NumberFormatException e) {

            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private com.raven.swingAbonne.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swingAbonne.Table table;
    // End of variables declaration//GEN-END:variables
}
