/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.formAbonne;


import biblio.AbonneService;
import biblio.Dictionnaire;
import static biblio.EmployeService.getConnection;
import biblio.Livre;
import biblio.Magazine;
import biblio.Ouvrage;
import com.raven.modelAbonne.StatusType;
import static com.raven.service.ServiceUser.userID;
import com.raven.swingAbonne.ScrollBar;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author USER
 *  int ouvrageId
 */
public class ReserverOuvrage extends javax.swing.JPanel {
 int ouvrageId;

    /**
     * Creates new form ReserverOuvrage
     */
    public ReserverOuvrage() {
         initComponents();
        //  add row table
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
         Vector<Ouvrage> o = new Vector<>();
         String debut=null;
            table.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) { 
                    JTable target = (JTable)e.getSource();
                    int selectedRow = target.getSelectedRow();
                     ouvrageId = (int)table.getValueAt(selectedRow, 0);
                    jTextField2.setText(String.valueOf(ouvrageId));
                }
            }
        });
    
         String type;
            try {
                 AbonneService g = new AbonneService();
                o=g.AfficherOuvrageARerserver();
            for (Ouvrage ouv : o) {
                 int id=ouv.getId();
                 String titre=ouv.getTitre();
                 String genre=ouv.getGenre();
                 DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                 String formattedDate = ouv.getDate_publication().format(formatter);
                   if (ouv instanceof Livre)
                   {
                       type="Livre";
                   }
                   else if (ouv instanceof Dictionnaire)
                   {
                       type="Dictionnaire";

                   }
                   else if (ouv instanceof Magazine)
                   {
                       type="Magazine";

                   }
                   else 
                   {
                       type="Livre Audio";

                   }
                table.addRow(new Object[]{id,type+"  "+genre,titre,genre,formattedDate,StatusType.APPROVED });
                  }
            }
            catch (NumberFormatException e) {
            }
            
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.raven.swingAbonne.PanelBorder();
        jLabel4 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table = new com.raven.swingAbonne.Table();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder1.setBackground(new java.awt.Color(229, 210, 158));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 127, 127));
        panelBorder1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        spTable.setBorder(null);

        table.setBackground(new java.awt.Color(229, 210, 158));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_ouvrage", "type   genre", "titre", "date_publication"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(table);

        panelBorder1.add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 590, 340));

        jLabel1.setForeground(new java.awt.Color(101, 61, 3));
        jLabel1.setText("Reserver");
        panelBorder1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 120, -1));

        jLabel3.setForeground(new java.awt.Color(101, 61, 3));
        jLabel3.setText("OUVRAGE_ID");
        panelBorder1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        jTextField2.setBackground(new java.awt.Color(242, 242, 242));
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panelBorder1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 171, -1));

        jToggleButton1.setBackground(new java.awt.Color(154, 113, 21));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(242, 242, 242));
        jToggleButton1.setText("reserve");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        panelBorder1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 120, 30));

        jLabel6.setForeground(new java.awt.Color(101, 61, 3));
        jLabel6.setText("Resultat");
        panelBorder1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 140, 30));

        add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 930, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesabonnes/background books (2).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
         if(table.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un ouvrage.", "Erreur", JOptionPane.ERROR_MESSAGE);
        } 
         else
         {
        LocalDateTime date_retour ;
         String ouv_d  = jTextField2.getText();
        String regexNumeric = "\\d+";
        int ouvr_id2 = Integer.parseInt(jTextField2.getText());
        if (ouv_d.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez cliquer sur une ligne.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            Boolean o;
            String debut=null;
            String type;
            try {
                LocalDate dateAujourdhui=LocalDate.now();
                AbonneService g = new AbonneService();
                System.out.println(ouvrageId);
                date_retour=g.reserverOuvrage(userID, ouvrageId);
                if (date_retour !=null)
                {
                 JOptionPane.showMessageDialog(null, "LIVRE RESERVE , IL SERA PRET LE"+date_retour, "Erreur", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Veuillez saisir un id_ouvrage et id_abonne disponnible", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch (NumberFormatException e) {
                
            }
        }
         }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private com.raven.swingAbonne.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swingAbonne.Table table;
    // End of variables declaration//GEN-END:variables
}
