/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.main;

import com.raven.projet_java_s2.abonne;
import com.raven.projet_java_s2.employee_service;
import static com.raven.service.ServiceUser.userID;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author USER
 */
public class InterfacePourNouvelAbonne extends javax.swing.JFrame {

    /**
     * Creates new form InterfacePourNouvelAbonne
     */
    public InterfacePourNouvelAbonne() {
        initComponents();
              getContentPane().setBackground(Color.WHITE);
            jLabel3.setForeground(Color.BLACK);
            jLabel4.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
            jLabel6.setForeground(Color.BLACK);
            jLabel10.setForeground(Color.BLACK);
            jLabel11.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ajoutimage = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        txtCin = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        txtType = new javax.swing.JComboBox<>();
        date1 = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ajoutimage1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Warning4 = new javax.swing.JLabel();
        Warning5 = new javax.swing.JLabel();
        Warning6 = new javax.swing.JLabel();
        Warning9 = new javax.swing.JLabel();
        Warning10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNom1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        ajoutimage.setLabel("button1");
        ajoutimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutimageActionPerformed(evt);
            }
        });

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 255));

        txtCin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCinActionPerformed(evt);
            }
        });

        txtPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrenomActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setText("Ajouter");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "normal", "premium" }));
        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CIN");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nom");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prenom");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date de Naissnace");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Type d'abonnement");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Informations sur les abonnement");

        ajoutimage1.setLabel("Confirmer image");
        ajoutimage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutimage1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Inserer une image");

        Warning4.setForeground(new java.awt.Color(255, 0, 0));

        Warning5.setForeground(new java.awt.Color(255, 0, 0));

        Warning6.setForeground(new java.awt.Color(255, 0, 0));

        Warning9.setForeground(new java.awt.Color(255, 0, 0));

        Warning10.setForeground(new java.awt.Color(255, 0, 0));

        jLabel13.setText("AJOUTER ABONNE");

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Commencer l'aventure");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajoutimage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(386, 386, 386))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jButton1))
                                        .addGap(27, 27, 27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Warning6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Warning9)
                                            .addComponent(Warning5)
                                            .addComponent(Warning10)
                                            .addComponent(Warning4))
                                        .addGap(65, 65, 65))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(220, 220, 220)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCin, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(txtPrenom))
                    .addContainerGap(673, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Warning10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Warning9)
                        .addGap(18, 18, 18)
                        .addComponent(Warning4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Warning5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(Warning6)
                                .addGap(8, 8, 8)
                                .addComponent(txtNom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addGap(9, 9, 9)
                        .addComponent(jButton2)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(ajoutimage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(txtCin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(260, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCinActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCinActionPerformed

    private void txtPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrenomActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       nbre_clique++;
        abonne a = new abonne(0);
        boolean pass=true;
        if((!com.raven.go.Tools.verifNumeric(txtCin.getText())) || txtCin.getText().length()!=8)
        {
            txtCin.setText("");
            Warning10.setText("Valeur Non Valide");
            Warning10.setForeground(Color.RED);
            pass=false;
        }
        else{
            Warning10.setText("Valeur Valide");
            Warning10.setForeground(Color.GREEN);
        }
        if(!com.raven.go.Tools.verifAlpha(txtNom1.getText()) || txtNom1.getText().isEmpty())
        {
            txtNom1.setText("");
            Warning4.setText("Valeur Non Valide");
            Warning4.setForeground(Color.RED);
            pass=false;
        }
        else{
            Warning4.setText("Valeur Valide");
            Warning4.setForeground(Color.GREEN);
        }
        if(!com.raven.go.Tools.verifAlpha(txtPrenom.getText())|| txtPrenom.getText().isEmpty())
        {
            txtPrenom.setText("");
            Warning9.setText("Valeur Non Valide");
            Warning9.setForeground(Color.RED);
            pass=false;
        }
        else{
            Warning9.setText("Valeur Valide");
            Warning9.setForeground(Color.GREEN);
        }
        try{
            if(date1.getDate().after(java.sql.Date.valueOf(LocalDate.now())) || null==date1.getDate())
            {
                date1.setDate(null);
                Warning5.setText("Valeur Non Valide");
                Warning5.setForeground(Color.RED);
                pass=false;
            }
            else{
                Warning5.setText("Valeur Valide");
                Warning5.setForeground(Color.GREEN);
            }
        }catch(Exception ex)
        {
            date1.setDate(null);
            Warning5.setText("Valeur Non Valide");
            Warning5.setForeground(Color.RED);
            pass=false;
        }
        String item =(String)txtType.getSelectedItem();
        String abb ;
        if(!com.raven.go.Tools.verifAbonnement(item))
        {
            Warning6.setText("Valeur Non Valide");
            Warning6.setText(item);
            Warning6.setForeground(Color.RED);
            pass=false;
        }
        else{
            switch (item) {
                case "normal":
                abb="normal";
                break;
                case "premium":
                abb="premium";
                break;
            }
            Warning6.setText("Valeur Valide");

            Warning6.setForeground(Color.GREEN);
        }
      
        if(pass==true)
        {
            LocalDate date_deb=LocalDate.now();
             LocalDate date_fin=LocalDate.now().plusYears(1);
             System.out.println(userID);
             a.setAbonne_id(userID);
            a.setCin(Integer.parseInt(txtCin.getText()));
            a.setDate_debut_abonnement(date_deb);
            a.setDate_fin_abonnement(date_fin);
            a.setDate_naissance(date1.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate());
            a.setNom(txtNom1.getText());
            a.setPrenom(txtPrenom.getText());
            a.setType_abonnement(item);
            employee_service.insert_abonne(a);
            
            
        }
        else{
            JOptionPane.showMessageDialog(null,"Fill the Form correctly");
        }

        //Object data1[]={txtId.getText(),txtCin.getText(),txtNom.getText(),txtPrenom.getText(),date1.getDate(),txtType.getText(),date2.getDate(),date3.getDate()};
        //model.addRow(data1);

    }//GEN-LAST:event_btnAddActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void ajoutimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutimageActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select an image");
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files", "jpg", "png", "gif", "jpeg");
        fileChooser.addChoosableFileFilter(filter);
          String cin = txtCin.getText();

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                java.awt.Image originalImage = ImageIO.read(selectedFile);
                // Convert the original image to BufferedImage
                BufferedImage bufferedImage = new BufferedImage(originalImage.getWidth(null), originalImage.getHeight(null), BufferedImage.TYPE_INT_RGB);
                Graphics2D g2 = bufferedImage.createGraphics();
                g2.drawImage(originalImage, 0, 0, null);
                g2.dispose();

                // Use the BufferedImage for ImageIcon
                ImageIcon imageIcon = new ImageIcon(bufferedImage.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), java.awt.Image.SCALE_SMOOTH));
                jLabel18.setIcon(imageIcon);

                // Prepare the image for saving
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                String extension = selectedFile.getName().substring(selectedFile.getName().lastIndexOf(".") + 1);
                ImageIO.write(bufferedImage, extension, baos);
                byte[] imageInByte = baos.toByteArray();

                // Save the image to the database
                saveImageToDatabase(imageInByte,cin);

            } catch (IOException | SQLException ex) {
                Logger.getLogger(InterfacePourNouvelAbonne.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ajoutimageActionPerformed

    private void ajoutimage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutimage1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select an image");
        fileChooser.setAcceptAllFileFilterUsed(false);
                  String cin = txtCin.getText();

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files", "jpg", "png", "gif", "jpeg");
        fileChooser.addChoosableFileFilter(filter);

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                java.awt.Image originalImage = ImageIO.read(selectedFile);
                BufferedImage bufferedImage = new BufferedImage(originalImage.getWidth(null), originalImage.getHeight(null), BufferedImage.TYPE_INT_RGB);
                Graphics2D g2 = bufferedImage.createGraphics();
                g2.drawImage(originalImage, 0, 0, null);
                g2.dispose();

                // Use the BufferedImage for ImageIcon
                ImageIcon imageIcon = new ImageIcon(bufferedImage.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), java.awt.Image.SCALE_SMOOTH));
                jLabel18.setIcon(imageIcon);

                // Prepare the image for saving
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                String extension = selectedFile.getName().substring(selectedFile.getName().lastIndexOf(".") + 1);
                ImageIO.write(bufferedImage, extension, baos);
                byte[] imageInByte = baos.toByteArray();

                // Save the image to the database
                saveImageToDatabase(imageInByte,cin);

            } catch (IOException | SQLException ex) {
                Logger.getLogger(InterfacePourNouvelAbonne.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ajoutimage1ActionPerformed
 int nbre_clique=0;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (nbre_clique>0)
        {
            MainAbonne m=new MainAbonne();
            m.setVisible(true);
                
        }
    }//GEN-LAST:event_jButton2ActionPerformed
private void saveImageToDatabase(byte[] image, String cin) throws SQLException {
    try (java.sql.Connection connection = LIBRAIRIE.getConnection();
         PreparedStatement pst = connection.prepareStatement("Update  abonne set image=? where  cin=?")) {
       pst.setInt(2, parseInt(cin));
        pst.setBytes(1, image);
        pst.executeUpdate();
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePourNouvelAbonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePourNouvelAbonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePourNouvelAbonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePourNouvelAbonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePourNouvelAbonne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Warning10;
    private javax.swing.JLabel Warning4;
    private javax.swing.JLabel Warning5;
    private javax.swing.JLabel Warning6;
    private javax.swing.JLabel Warning9;
    private java.awt.Button ajoutimage;
    private java.awt.Button ajoutimage1;
    private javax.swing.JButton btnAdd;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCin;
    private javax.swing.JTextField txtNom1;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JComboBox<String> txtType;
    // End of variables declaration//GEN-END:variables
}
