/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.main;

import com.raven.event.EventMenuSelected;
import com.raven.formAbonne.AnnulerReservation;
import com.raven.formAbonne.CommenterOuvrage;
import com.raven.formAbonne.EmprunterLivre;
import com.raven.formAbonne.Form_Home1;
import com.raven.formAbonne.GetAllMesCommentaires;
import com.raven.formAbonne.GetAllOuvrages;
import com.raven.formAbonne.Mesnotifications;
import com.raven.formAbonne.MonCompte;
import com.raven.formAbonne.RecupererLivreReserve;
import com.raven.formAbonne.ReserverOuvrage;
import com.raven.formAbonne.RetournerLivre;
import com.raven.formAbonne.VoirMesEmprunts;
import java.awt.Color;
import java.util.HashSet;
import javax.swing.JComponent;

/**
 *
 * @author RAVEN
 */
public class MainAbonne extends javax.swing.JFrame {

    /**
     * Creates new form MainAbonne
     */
    private Form_Home1 home;
    private GetAllOuvrages form1;
    private VoirMesEmprunts form2;
    private GetAllMesCommentaires form3;
    private ReserverOuvrage form4;
    private RecupererLivreReserve form5;
    private Mesnotifications form6;
    private EmprunterLivre form7;
    private RetournerLivre form8;
    private MonCompte form9;
    private CommenterOuvrage form10;
    private  AnnulerReservation form11;


    public MainAbonne() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        home = new Form_Home1();
        form1 = new GetAllOuvrages();
        form2 = new VoirMesEmprunts();
        form3 = new GetAllMesCommentaires();
        form4 = new ReserverOuvrage();
        form5 = new RecupererLivreReserve();
       form6 = new Mesnotifications();
       form7 = new EmprunterLivre();
       form8 = new RetournerLivre();
       form9 = new MonCompte();
       form10 = new CommenterOuvrage();
              form11 = new AnnulerReservation();


        menu.initMoving(MainAbonne.this);
        menu.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
                if (index == 0) {
                    setForm(home);
                } else if (index == 1) {
                    setForm(form1);
                } else if (index == 2) {
                    setForm(form2);
                } else if (index == 3) {
                    setForm(form2);
                }
                 else if (index == 4) {
                    setForm(form2);
                }
                else if (index == 5) {
                    setForm(form7);
                }
                else if (index == 6) {
                    setForm(form8);
                }
                else if (index == 7) {
                    setForm(form8);
                }
                else if (index == 9) {
                    setForm(form3);
                }
                 else if (index == 10) {
                    setForm(form10);
                }
              
              
                 else if (index == 13) {
                    setForm(form4);
                }
                else if (index == 14) {
                    setForm(form5);
                }
                   else if (index == 15) {
                    setForm(form11);
                }
                 else if (index == 18) {
                    setForm(form6);
                }
                 else if (index == 21) {
                    setForm(form9);
                }
                
            }
        });
        //  set when system open start with home form
        setForm(new Form_Home1());
    }

    private void setForm(JComponent com) {
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.raven.swingAbonne.PanelBorder();
        menu = new com.raven.component.Menu2();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1079, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAbonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAbonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAbonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAbonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAbonne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private com.raven.component.Menu2 menu;
    private com.raven.swingAbonne.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
