
package com.raven.main;
import com.raven.event.EventMenuSelected;
import com.raven.form.AbonneEmployee;
import com.raven.form.AfficherEmployee;
import com.raven.form.AfficherEmprunts;
import com.raven.form.AfficherReservation;
import com.raven.form.AjouterEmprunt;
import com.raven.form.AjouterOuvrage;
import com.raven.form.ConsulterHistorique;
import com.raven.form.Form_Home;
import com.raven.form.GererOuvrage;
import com.raven.form.ManipuleEmployee;
import com.raven.form.ModifierOuvrage;
import com.raven.form.MonCompte;
import com.raven.form.RecupererLivreReserve;
import com.raven.form.RecupererLivreReserve3;
import com.raven.form.ReserverOuvrage;
import com.raven.form.RetournerLivre;
import com.raven.form.SignalerVol;
import com.raven.form.SupprimerOuvrage;
import com.raven.form.VoirReclamation;
import java.awt.Color;
import javax.swing.JComponent;

/**
 *
 * @author RAVEN
 */
public class MainEmployeNormal extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private Form_Home home;
    private GererOuvrage form4;
    private AfficherEmployee form2;
    private AfficherEmprunts form3;
    private SupprimerOuvrage form5;
    private ModifierOuvrage form6;
     private ManipuleEmployee form7;
     private AbonneEmployee form8;
     private AfficherReservation form9;
     private AjouterOuvrage form10;
     private AjouterEmprunt form11;
     private RetournerLivre form12;
     private ReserverOuvrage form13;
     private SignalerVol form14;
     private ConsulterHistorique form15;
   private RecupererLivreReserve3 form16;
      private MonCompte form17;
            private VoirReclamation form18;


    public MainEmployeNormal() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        home = new Form_Home();
        form2 = new AfficherEmployee();
        form3 = new AfficherEmprunts();
        form4=new GererOuvrage();
        form5=new SupprimerOuvrage();
        form6=new ModifierOuvrage();
        form7=new ManipuleEmployee();
        form8=new AbonneEmployee();
        form9=new AfficherReservation();
         form10=new AjouterOuvrage();
         form11=new AjouterEmprunt();
         form12=new RetournerLivre();
         form13=new ReserverOuvrage();
         form14=new SignalerVol();
         form15=new ConsulterHistorique();
         form16=new RecupererLivreReserve3();
         form17=new MonCompte();
         form18=new VoirReclamation();
        menu.initMoving(MainEmployeNormal.this);
        menu.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
                if (index == 0) {
                    setForm(home);
                } else if (index == 1) {
                    setForm(form4);
                } else if (index == 2) {
                    setForm(form2);
                } else if (index == 3) {
                    setForm(form3);
                }
                else if (index == 5) {
                    
                    setForm(form2);
                
                }
                else if (index == 4) {        
                    setForm(form9);        
                }
                else if (index == 6) {
                    setForm(form10);
                }
                else if (index == 7) {
                    setForm(form5);
                }
                else if (index == 8) {
                    setForm(form6);
                }
               else if (index == 9) {
                    setForm(form14);
                }
                 else if (index == 11) {
                    setForm(form8);
                }
                else if (index == 12) {
                    setForm(form7);
                }
                  
                else if (index == 14) {
                    setForm(form11);
                }
                else if (index == 15) {
                    setForm(form12);
                }
                else if (index == 16) {
                    setForm(form13);
                }
                  else if (index == 17) {
                    setForm(form16);
                }
                 else if (index == 21) {
                    setForm(form15);
                }
                   else if (index == 22) {
                    setForm(form18);
                }
                else if (index == 24) {
                    setForm(form17);
                }
            }
        });
        //  set when system open start with home form
        setForm(new Form_Home());
    }

    public  void setForm(JComponent com) {
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.raven.swing.PanelBorder();
        menu = new com.raven.component.Menu();
        header2 = new com.raven.component.Header();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(header2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Header header2;
    private javax.swing.JPanel mainPanel;
    private com.raven.component.Menu menu;
    private com.raven.swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
